services:
  node1:
    image: kindest/node:development
    container_name: kubelet-node1
    privileged: true
    volumes:
      - ./kubernetes:/app/kubernetes:rw
      - ./vscode:/app/kubernetes/.vscode:rw
      - ./kubernetes/build/root/Makefile:/app/kubernetes/Makefile:ro
    environment:
      - KUBELET_FLAGS=--cgroups-per-qos=false --enforce-node-allocatable=
      - KUBECONFIG=/var/run/kubernetes/admin.kubeconfig
    working_dir: /app/kubernetes
    command: /usr/local/bin/entrypoint
