apiVersion: v1
kind: Pod
metadata:
  name: debug-shell
  namespace: default
spec:
  containers:
  - name: debug-container
    image: curlimages/curl
    command: [ "sleep", "infinity" ]
    stdin: true
    tty: true

