apiVersion: v1
kind: Pod
metadata:
  name: k6-load-generator
spec:
  containers:
  - name: k6
    image: grafana/k6:latest
    args:
    - run
    - /scripts/test.js
    volumeMounts:
    - name: k6-script
      mountPath: /scripts
  volumes:
  - name: k6-script
    configMap:
      name: k6-script

